happening_places/models/__init__.py
from category import Category
from listing import Hotspot
from user import User

happening_places/models/category.py
from happening_places import db

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    def __repr__(self):
        return self.name

happening_places/models/listing.py
from datetime import datetime

from happening_places import db


categories = db.Table('hotspot_category',
    db.Column('category_id', db.Integer, db.ForeignKey('category.id')),
    db.Column('hotspot_id', db.Integer, db.ForeignKey('hotspot.id'))
)

class Hotspot(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300), nullable=False)
    address = db.Column(db.String(700))
    description = db.Column(db.String(1000))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    status = db.Column(db.String(50), default='unverified')
    _categories = db.relationship(
        'Category',
        secondary=categories,
        backref=db.backref('hotspots', lazy='dynamic')
    )

    @staticmethod
    def get_user_listings(user_id):
        return Hotspot.query.filter_by(user_id=user_id).all()

    def __repr__(self):
        return "<Hotspot '{}' '{}'>".format(self.name, self.description)

happening_places/models/user.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash

from happening_places import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    password_hash = db.Column(db.String)
    firstname = db.Column(db.String(50))
    lastname = db.Column(db.String(50))
    email = db.Column(db.String(200), nullable=False, unique=True)
    username = db.Column(db.String(500), nullable=False, unique=True)
    status = db.Column(db.String(50), default='unverified')
    role = db.Column(db.String(50), default='user')
    hotspots = db.relationship('Hotspot', backref='user', lazy='dynamic')

    def __repr__(self):
        return "<User: '{}'>".format(self.username)

    @property
    def password(self):
        raise AttributeError('password: Write Only Field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()

happening_places/scripts/models.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash

from happening_places import db


categories = db.Table('hotspot_category',
    db.Column('category_id', db.Integer, db.ForeignKey('category.id')),
    db.Column('hotspot_id', db.Integer, db.ForeignKey('hotspot.id'))
)


class Hotspot(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300), nullable=False)
    address = db.Column(db.String(700))
    description = db.Column(db.String(1000))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    status = db.Column(db.String(50), default='unverified')
    _categories = db.relationship(
        'Category',
        secondary=categories,
        backref=db.backref('hotspots', lazy='dynamic')
    )

    @staticmethod
    def get_user_listings(user_id):
        return Hotspot.query.filter_by(user_id=user_id).all()

    def __repr__(self):
        return "<Hotspot '{}' '{}'>".format(self.name, self.description)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    password_hash = db.Column(db.String)
    firstname = db.Column(db.String(50))
    lastname = db.Column(db.String(50))
    email = db.Column(db.String(200), nullable=False, unique=True)
    username = db.Column(db.String(500), nullable=False, unique=True)
    status = db.Column(db.String(50), default='unverified')
    role = db.Column(db.String(50), default='user')
    hotspots = db.relationship('Hotspot', backref='user', lazy='dynamic')

    def __repr__(self):
        return "<User: '{}'>".format(self.username)

    @property
    def password(self):
        raise AttributeError('password: Write Only Field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    def __repr__(self):
        return self.name

happening_places/listings/forms.py
from flask_wtf import Form
from wtforms.fields import StringField
from wtforms.validators import InputRequired

from happening_places.models import Hotspot


class AddLocationForm(Form):
    name = StringField('name_of_hotspot', validators=[InputRequired()])
    address = StringField('address', validators=[InputRequired()])
    description = StringField('description', validators=[InputRequired()])

happening_places/scripts/forms.py
from flask_wtf import Form
from wtforms.fields import BooleanField
from wtforms.fields import PasswordField
from wtforms.fields import StringField
from wtforms.fields import SubmitField
from flask.ext.wtf.html5 import URLField, EmailField
from wtforms.validators import InputRequired, url, Email
from wtforms.validators import Regexp, Length, ValidationError

from models import User

class AddLocationForm(Form):
    name = StringField('name_of_hotspot', validators=[InputRequired()])
    address = StringField('address', validators=[InputRequired()])
    description = StringField('description', validators=[InputRequired()])


class SignUpForm(Form):
    email = EmailField('email', validators=[InputRequired(), Email()])
    firstname = StringField('firstname')
    lastname = StringField('lastname')
    username = StringField('username', validators=[
        InputRequired(),
        Length(3,50),
        Regexp('^[A-Za-z0-9_{3,}$]', message="Username must consist of only letters, numbers and underscores")
    ])
    password = PasswordField('password', validators=[InputRequired()])

    def validate_email(self, email_field):
        if User.query.filter_by(email=email_field.data).first():
            raise ValidationError('There is already a user with this email address.')

    def validate_username(self, username_field):
        if User.query.filter_by(username=username_field.data).first():
            raise ValidationError('This username is already taken')


class LoginForm(Form):
    username= StringField('Your Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    remember_me = BooleanField('Keep me Logged In')

happening_places/__init__.py
import os

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask.ext.moment import Moment
# from flask_debugtoolbar import DebugToolbarExtension

from .config import config_by_name


# Initialize And Configure App Extensions
db = SQLAlchemy()
moment = Moment()
# toolbar = DebugToolbarExtension()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])

    # Install App Extensions
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    # toolbar.init_app(app)

    from .auth import auth as auth_blueprint
    from .listings import listing as listing_blueprint
    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint, url_prefix='/')
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(listing_blueprint, url_prefix='/listings')

    return app

happening_places/listings/__init__.py
from flask import Blueprint

listing = Blueprint('listing', __name__)

from . import views

happening_places/listings/views.py
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required

from . import listing
from .forms import AddLocationForm
from happening_places import db
from happening_places.models import Hotspot


@listing.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = AddLocationForm()
    if form.validate_on_submit():
        hotspot = Hotspot(
            name = form.name.data,
            address = form.address.data,
            description = form.description.data,
            user = current_user
        )
        db.session.add(hotspot)
        db.session.commit()
        print "saved.."
        return redirect(url_for('main.index'))
    return render_template('add.html', form=form)


@listing.route('/all')
def listings():
    return render_template('listings.html')

happening_places/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

happening_places/main/views.py
from flask import render_template

from . import main
from happening_places import login_manager
from happening_places.models import Hotspot
from happening_places.models import User


@login_manager.user_loader
def get_user(uid):
    return User.query.get(int(uid))


@main.route('/')
def index():
    listings = Hotspot.query.all()
    return render_template('index.html', new_listings=listings)


@main.route('/confirmation')
def confirmation():
    return render_template('confirmation.html')


@main.route('/categories')
def categories():
    return render_template('categories.html')


@main.route('/directories')
def directories():
    return render_template('directories.html')


@main.app_errorhandler(403)
def server_error(e):
    return render_template('403.html'), 403


@main.app_errorhandler(404)
def route_not_found(e):
    return render_template('404.html'), 404


@main.app_errorhandler(500)
def server_error(e):
    return render_template('500.html'), 500


@main.app_context_processor
def server_error():
    return dict(all_tags=[
        'lifestyle',
        'hotels',
        'bars',
        'supermarkets',
        'movies',
        'outdoors'
    ])

happening_places/templates/add.html
{% extends 'base.html' %}
{% block content %}
  <br><br><br><br>
  <div class="ui raised very padded text container segment">

    <h3 class="ui dividing header">
      Add New location
    </h3>
    <br>

    <form class="ui form" action="/listings/add" method="POST">
      {{ form.hidden_tag() }}
      <div class="field">
        <label>Hotspot Name</label>
        {{ form.name }}
        {% if form.name.errors %}
        {% for error in form.name.errors %}
        <div class="ui pointing red basic label">
          {{ error }}
        </div>
        {% endfor %}
        {% endif%}
      </div>
      <div class="field">
        <label>Address</label>
        {{ form.address }}
        {% if form.address.errors %}
        {% for error in form.address.errors %}
        <div class="ui pointing red basic label">
          {{ error }}
        </div>
        {% endfor %}
        {% endif%}
      </div>
      <div class="field">
        <label>Description</label></label>
        {{ form.description }}
        {% if form.description.errors %}
        {% for error in form.description.errors %}
        <div class="ui pointing red basic label">
          {{ error }}
        </div>
        {% endfor %}
        {% endif%}
      </div>

      <button class="ui basic button" type="submit">
        <i class="icon send"></i>
        Submit
      </button>
    </form>

  </div>

{% endblock %}

happening_places/templates/base.html
{% from "macros.html" import nav_link with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Falade Ayodeji Mayowa">
    <meta name="description" content="Find Fun Places To Hangout in Lagos">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/semantic-ui/dist/semantic.min.css') }}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" media="screen" title="no title" charset="utf-8">
  </head>
  <body>
    <div class="ui secondary pointing menu">

      {{ nav_link('main.index', 'Gidi-Spots') }}
      {{ nav_link('main.directories', 'Directories') }}
      {{ nav_link('listing.listings', 'Listings') }}

      <a class="ui item padding-bottom-sm {% if request.path == '/add' %} active {% endif %}" href="{{ url_for('listing.add') }}">
        <div class="ui icon button" data-content="Add users to your feed">
          <i class="add icon"></i>
        </div>
      </a>

      <div class="right menu">
        {% if current_user.is_authenticated %}
          {{ nav_link('auth.dashboard', 'Dashboard') }}
          {{ nav_link('auth.logout', 'Logout') }}
          <a class="ui item"></a>
        {% else %}
          {{ nav_link('auth.login', 'Login') }}
          {{ nav_link('auth.signup', 'Signup') }}
        {% endif %}
      </div>
    </div>
    <div class="">
      {% block content %}
      {% endblock %}
    </div>

    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}

    <script type="text/javascript" src="{{ url_for('static', filename='libs/semantic-ui/dist/semantic.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

happening_places/templates/confirmation.html
{% extends 'base.html' %}
{% block content %}
  <br><br><br>
    <div class="ui small container">
      <div class="ui icon teal message">
        <i class="inbox icon"></i>
        <div class="content">
          <div class="header">
            Yikes! Your listing has been added
          </div>
        </div>
      </div>
    </div>

{% endblock %}

happening_places/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
  Dashboard
{% endblock %}

{% block content %}
<div class="ui very padded segment margin-top-lg full-height">

<div class="ui grid">
  <div class="four wide column">
    <div class="ui vertical fluid tabular menu">

      {{ nav_link('auth.dashboard', 'Your Listings') }}
      {{ nav_link('main.index', 'Account Settings') }}
      {{ nav_link('main.index', 'Notifications') }}
      {{ nav_link('main.index', 'Extra link 1') }}
      {{ nav_link('main.index', 'Extra link 2') }}
      {{ nav_link('main.index', 'Extra link 3') }}

    </div>
  </div>
  <div class="twelve wide stretched column">
    <div class="ui content">
      {% if listings %}
        {% include 'partials/dashboard_listings_table.html' %}
      {% else %}
      <div class="ui text container">
        <h2>
          You are yet to add any listings.. Click here to get started.
        </h2>
      </div>
      {% endif %}
    </div>
  </div>
</div>
</div>

{% endblock %}

happening_places/templates/directories.html
{% extends 'base.html' %}

{% block title %}
  Gidispot directories
{% endblock %}


{% block content %}
  <div class="ui container margin-top-lg">
    <div class="ui raised very padded text dividing segment">
      <h3 class="ui header">Find our Directories below</h3>
      <p>Looking for a place to have a nice time in Lagos??</p>
      <p>This is the right place for you.</p>
      <p>
        Search through our repository of awesome places in Gidi.
      </p>
      <p>
        Rememeber to share this with your friends.
      </p>
      <p>
        <a href="{{ url_for('listing.add') }}">Add new listing</a>
      </p>
    </div>
  </div>

{% endblock %}

happening_places/templates/index.html
{% extends 'base.html' %}

{% block title %}
Welcome To Gidi-Spots
{% endblock %}


{% block content %}
  <div class="ui vertical well-padded masthead center aligned segment margin-fix">
    <h2 class="ui header">Welcome to Gidi-Spots</h2>
    <h5>Looking for a fun place to hangout in Lagos ?</h5>
    <h5>Search through our repository of awesome places in Gidi.</h5>
    <h3><a href="{{ url_for('listing.add') }}">Add new listing</a></h3>
  </div>

  {% if new_listings %}
  <div class="listings-container">
    <div class="ui container">
      <div class="trending">
        <div class="ui center aligned grid vertical-padding">
          <h2 class="header">Hot Picks</h2>
        </div>
        <div class="ui three cards">
          {% for listing in new_listings %}
            {% include 'partials/listing_card.html' %}
          {% endfor %}
        </div>
      </div>
      <hr>
      <div class="trending">
        <div class="ui center aligned grid vertical-padding">
          <h2 class="header">Trending Listings</h2>
        </div>
        <div class="ui three cards">
          {% for listing in new_listings %}
            {% include 'partials/listing_card.html' %}
          {% endfor %}
        </div>
      </div>
      <hr>
      <div class="recent">
        <div class="ui center aligned grid vertical-padding">
          <h2 class="header">Recent Listings</h2>
        </div>
        <div class="ui three cards">
          {% for listing in new_listings %}
            {% include 'partials/listing_card.html' %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% else %}

  <div class="ui container">
    <br><br><br><br>
    <div class="ui teal message">There are currently no listings on this application.</div>
  </div>
{% endif %}

{% endblock %}

happening_places/templates/listings.html
{% extends 'base.html' %}

{% block title %}
  Gidispot listings
{% endblock %}


{% block content %}
<div class="ui container margin-top-lg">
  <div class="ui raised very padded text dividing segment">
    <h3 class="ui header">Find our Listings below</h3>
    <p>Looking for a place to have a nice time in Lagos??</p>
    <p>This is the right place for you.</p>
    <p>
      Search through our repository of awesome places in Gidi.
    </p>
    <p>
      Rememeber to share this with your friends.
    </p>
    <p>
      <a href="{{ url_for('listing.add') }}">Add new listing</a>
    </p>
  </div>
</div>

{% endblock %}

happening_places/templates/login.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}

<br><br><br>
<div class="ui raised very padded text container segment">
  <div class="header centered">
    <h2>Welcome to Gidi-Spots!</h2>
    <br>
  </div>
  <div class="ui attached center aligned grid message">
    <p>Login to your account</p>
  </div>
  <form class="ui form attached fluid segment" action="/auth/login" method="POST">
    {{ form.hidden_tag() }}
    <div class="field">
      <label>Username</label>
      {{ form.username }}
      {% if form.username.errors %}
      <div class="ui pointing red basic label">
        {% for error in form.username.errors %}
        {{error}}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="field">
      <label>Password</label>
      {{ form.password }}
      {% if form.password.errors %}
      <div class="ui pointing red basic label">
        {% for error in form.password.errors %}
        {{error}}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="field">
      <div class="ui checkbox">
        {{ form.remember_me }}
        <label>Keep me logged in.</label>
      </div>
    </div>
    <button class="ui basic button" type="submit">
      <i class="icon send"></i>
      Submit
    </button>
  </form>
  <div class="ui bottom attached warning message">
    <i class="icon help"></i>
    Don't have an account yet? <a href="{{ url_for('auth.signup') }}">Signup here</a>.
  </div>
</div>
m
{% endblock %}

happening_places/templates/macros.html
{% macro nav_link(path, text) %}
    {% if request.endpoint and request.endpoint.endswith(path) %}
      <a class="item active" href="{{ url_for(path) }}">{{ text }}</a>
    {% else %}
      <a class="item" href="{{ url_for(path) }}">{{ text }}</a>
    {% endif %}
{% endmacro %}

happening_places/templates/signup.html
{% extends 'base.html' %}

{% block title %}
  Signup for Gidi-Spots
{% endblock %}


{% block content %}
<br><br><br>
<div class="ui raised very padded text container segment">
  <div class="header centered">
    <h2>Welcome to Gidi-Spots!</h2>
    <br>
  </div>
  <div class="ui attached center aligned grid message">
    <p>Sign up to start spottin ;)</p>
  </div>
  <form class="ui form attached fluid segment" action="/signup" method="POST">
    {{ form.hidden_tag() }}
    <div class="two fields">
      <div class="field">
        <label>First Name</label>
        {{ form.firstname }}
        {% if form.firstname.errors %}
        <div class="ui pointing red basic label">
          {% for error in form.firstname.errors %}
          {{error}}
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="field">
        <label>Last Name</label>
        {{ form.lastname }}
        {% if form.lastname.errors %}
        <div class="ui pointing red basic label">
          {% for error in form.lastname.errors %}
          {{error}}
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
    <div class="field">
      <label>Username</label>
      {{ form.username }}
      {% if form.username.errors %}
      <div class="ui pointing red basic label">
        {% for error in form.username.errors %}
        {{error}}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="field">
      <label>Email</label>
      {{ form.email }}
      {% if form.email.errors %}
      <div class="ui pointing red basic label">
        {% for error in form.email.errors %}
        {{error}}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="field">
      <label>Password</label>
      {{ form.password }}
      {% if form.password.errors %}
      <div class="ui pointing red basic label">
        {% for error in form.password.errors %}
        {{error}}
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <button class="ui basic button" type="submit">
      <i class="icon send"></i>
      Submit
    </button>
    <br>
    <br>

  </form>
  <div class="ui bottom attached warning message">
    <i class="icon help"></i>
    Already signed up? <a href="{{ url_for('auth.login') }}">Login here</a> instead.
  </div>
</div>
{% endblock %}